name: Deploy Galton Board

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install pygbag
      run: pip install pygbag

    - name: Build with pygbag
      run: pygbag --build .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages            # <-- this line ensures branch is created
        publish_dir: ./build/web
        force_orphan: true                  # <-- makes a clean gh-pages branch 